spring:
  application:
    name: kafka-chat-backend
  kafka:
    bootstrap-servers: 127.0.0.1:9094
    consumer:
      group-id: ${random.uuid}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: health,info
otel:
  metric:
    export:
      interval: 500
  service:
    name: kafka-chat-backend
